CREATE SCHEMA IF NOT EXISTS `productms` DEFAULT CHARACTER SET utf8 ;
USE `productms` ;

CREATE TABLE IF NOT EXISTS `productms`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
